Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DMIN_new_amazon4: # This is a config template
    model: DMIN
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    aux_hidden_units: [30, 15]
    aux_activation: "ReLU"
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    enable_sum_pooling: False
    use_behavior_refiner: False
    num_heads: 1
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    aux_loss_lambda: 0
    use_pos_emb: False
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DMIN_new_douban4: # This is a config template
    model: DMIN
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    aux_hidden_units: [30, 15]
    aux_activation: "ReLU"
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    enable_sum_pooling: False
    use_behavior_refiner: False
    num_heads: 1
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    aux_loss_lambda: 0
    use_pos_emb: False
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DMIN_new_ml10m4: # This is a config template
    model: DMIN
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    aux_hidden_units: [30, 15]
    aux_activation: "ReLU"
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    enable_sum_pooling: False
    use_behavior_refiner: False
    num_heads: 1
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    aux_loss_lambda: 0
    use_pos_emb: False
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
