Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null


DIEN_new_amazon: # This is a config template
    model: DIEN
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: Dice
    net_dropout: 0
    dien_target_field: ItemID
    dien_sequence_field: click_seq
    dien_neg_seq_field: []
    gru_type: AUGRU
    enable_sum_pooling: False
    attention_type: bilinear_attention
    attention_hidden_units: [80, 40]
    attention_activation: "ReLU"
    attention_dropout: 0
    use_attention_softmax: True
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    aux_loss_alpha: 0
    batch_norm: True
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DIEN_new_douban: # This is a config template
    model: DIEN
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: Dice
    net_dropout: 0
    dien_target_field: ItemID
    dien_sequence_field: click_seq
    dien_neg_seq_field: []
    gru_type: AUGRU
    enable_sum_pooling: False
    attention_type: bilinear_attention
    attention_hidden_units: [80, 40]
    attention_activation: "ReLU"
    attention_dropout: 0
    use_attention_softmax: True
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    aux_loss_alpha: 0
    batch_norm: True
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DIEN_new_ml10m: # This is a config template
    model: DIEN
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: Dice
    net_dropout: 0
    dien_target_field: ItemID
    dien_sequence_field: click_seq
    dien_neg_seq_field: []
    gru_type: AUGRU
    enable_sum_pooling: False
    attention_type: bilinear_attention
    attention_hidden_units: [80, 40]
    attention_activation: "ReLU"
    attention_dropout: 0
    use_attention_softmax: True
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    aux_loss_alpha: 0
    batch_norm: True
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
  