Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DMR_new_amazon2:
    model: DMR
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    batch_norm: False
    bn_only_once: False
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    context_field: null
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    enable_sum_pooling: False
    enable_u2i_rel: True
    enable_i2i_rel: False
    aux_loss_beta: 0
    use_pos_emb: False
    pos_emb_dim: 8
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DMR_new_douban2:
    model: DMR
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    batch_norm: False
    bn_only_once: False
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    context_field: null
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    enable_sum_pooling: False
    enable_u2i_rel: True
    enable_i2i_rel: False
    aux_loss_beta: 0
    use_pos_emb: False
    pos_emb_dim: 8
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DMR_new_ml10m2:
    model: DMR
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [32, 16]
    dnn_activations: "ReLU"
    net_dropout: 0
    batch_norm: False
    bn_only_once: False
    target_field: ItemID
    sequence_field: click_seq
    neg_seq_field: null
    context_field: null
    attention_hidden_units: [20, 10]
    attention_activation: "ReLU"
    attention_dropout: 0
    enable_sum_pooling: False
    enable_u2i_rel: True
    enable_i2i_rel: False
    aux_loss_beta: 0
    use_pos_emb: False
    pos_emb_dim: 8
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
