Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DIN_new_amazon4: # This is a config template
    model: DIN
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [32]
    attention_hidden_activations: "ReLU"
    attention_output_activation: null
    attention_dropout: 0.1
    din_target_field: ItemID
    din_sequence_field: click_seq
    din_use_softmax: True
    net_dropout: 0.1
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DIN_new_douban4: # This is a config template
    model: DIN
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [32]
    attention_hidden_activations: "ReLU"
    attention_output_activation: null
    attention_dropout: 0.1
    din_target_field: ItemID
    din_sequence_field: click_seq
    din_use_softmax: True
    net_dropout: 0.1
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
DIN_new_ml10m4: # This is a config template
    model: DIN
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [32]
    attention_hidden_activations: "ReLU"
    attention_output_activation: null
    attention_dropout: 0.1
    din_target_field: ItemID
    din_sequence_field: click_seq
    din_use_softmax: True
    net_dropout: 0.1
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    