Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

WuKong_new_amazon:
    model: WuKong
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    num_layers: 2
    compression_dim: 8
    fmb_units: [32,32,32]
    fmb_dim: 16
    project_dim: 6
    dropout_rate: 0.2
    hidden_activations: relu
    mlp_hidden_units: [16]
    epochs: 1
    shuffle: True
    seed: 2000
    monitor: {'AUC':1, 'logloss':-1}
    monitor_mode: 'max'

WuKong_new_douban:
    model: WuKong
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    num_layers: 2
    compression_dim: 8
    fmb_units: [32,32,32]
    fmb_dim: 16
    project_dim: 6
    dropout_rate: 0.2
    hidden_activations: relu
    mlp_hidden_units: [16]
    epochs: 1
    shuffle: True
    seed: 2000
    monitor: {'AUC':1, 'logloss':-1}
    monitor_mode: 'max'

WuKong_new_ml10m:
    model: WuKong
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    num_layers: 2
    compression_dim: 8
    fmb_units: [32,32,32]
    fmb_dim: 16
    project_dim: 6
    dropout_rate: 0.2
    hidden_activations: relu
    mlp_hidden_units: [16]
    epochs: 1
    shuffle: True
    seed: 2000
    monitor: {'AUC':1, 'logloss':-1}
    monitor_mode: 'max'
