Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

xDeepFM_new_amazon2: # This is a config template
    model: xDeepFM
    dataset_id: amazon_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    cin_hidden_units: [10, 10]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
xDeepFM_new_douban2: # This is a config template
    model: xDeepFM
    dataset_id: douban_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    cin_hidden_units: [10, 10]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
xDeepFM_new_ml10m2: # This is a config template
    model: xDeepFM
    dataset_id: ml10m_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    cin_hidden_units: [10, 10]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
xDeepFM_new_txhq2: # This is a config template
    model: xDeepFM
    dataset_id: txhq_new
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    cin_hidden_units: [10, 10]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: False
    seed: 2000
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'